name: Run Web Proxy

on:
  workflow_dispatch:

jobs:
  run-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Run HTTP Proxy and Tunnel
        run: |
          # اجرای پروکسی با استفاده از Docker (خودکار و بدون نیاز به دانلود)
          docker run -d --rm -p 8080:8080 ghcr.io/snail007/goproxy:latest http -t tcp -p ":8080"
          sleep 3
          
          # نصب و اجرای bore
          curl -L -o bore https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          tar -xzf bore
          chmod +x bore
          ./bore local 8080 --to bore.pub
